# Fos user bundle routes

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


ProlixSocloneBundle_homepage:
    pattern:  /
    defaults: { _controller: ProlixSocloneBundle:Homepage:index}
    requirements:
        _method:  GET

ProlixSocloneBundle_question_index:
    pattern: /question
    defaults: { _controller: ProlixSocloneBundle:Question:index }
    requirements:
        _method: GET

ProlixSocloneBundle_question_show:
    pattern: /question/{id}
    defaults: { _controller: ProlixSocloneBundle:Question:show }
    requirements:
        _method: GET
        id: \d+

ProlixSocloneBundle_question_create:
    pattern:  /question/{question_id}
    defaults: { _controller: ProlixSocloneBundle:Question:create }
    requirements:
        _method:  POST
        blog_id: \d+


