ProlixSocloneBundle_homepage:
    pattern:  /
    defaults: { _controller: ProlixSocloneBundle:Homepage:index}
    requirements:
        _method:  GET

ProlixSocloneBundle_question_index:
    pattern: /question
    defaults: { _controller: ProlixSocloneBundle:Question:index }
    requirements:
        _method: GET

ProlixSocloneBundle_question_show:
    pattern: /question/{id}
    defaults: { _controller: ProlixSocloneBundle:Question:show }
    requirements:
        _method: GET
        id: \d+

ProlixSocloneBundle_question_create:
    pattern:  /question/{question_id}
    defaults: { _controller: ProlixSocloneBundle:Question:create }
    requirements:
        _method:  POST
        blog_id: \d+
